name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 우리가 아까 설치한 안정적인 버전인 20을 사용합니다.
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build -- --prefix-paths # pathPrefix 설정을 적용하여 빌드

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public # Gatsby가 빌드한 결과물이 담긴 폴더
          branch: gh-pages # 배포할 브랜치